{{ if .Values.monitorAllNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: grafana-sync
  namespace: {{ .Release.Namespace }}
{{ end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sync
